- hosts: "{{ variable_host | default('firehawkgateway') }}"
  remote_user: "{{ variable_connect_as_user | default('deployuser') }}"
  gather_facts: "{{ variable_gather_facts | default('false') }}"
  become_user: root
  become: true

  vars:
    state: started
    reboot: false
    
  roles:
  - deadline-db-restart
