---

- hosts: "{{ variable_host | default('ansible_control') }}"
  remote_user: "{{ variable_connect_as_user | default('deployuser') }}"
  gather_facts: "{{ variable_gather_facts | default('false') }}"
  become: true

  vars:
    variable_user: deadlineuser
    variable_uid: 9001
    variable_user_gid: "{{ variable_uid }}"
    variable_gid: "{{ syscontrol_gid }}"
    my_password: "{{ user_deadlineuser_pw | string | password_hash('sha512') }}"
    no_extension: "{{ deadline_linux_installers_tar | splitext | first }}"
    basename: "{{ no_extension.split('/')[-1] }}"
    houdini_major_version: 18.0
    sudo: true
  
  pre_tasks:
  - name: test connection as deployuser
    debug:
      msg: "connection established"

  - name: Collect some facts only for ansible_distribution
    setup:
      gather_subset:
        - '!all'
        - 'min'
    tags:
    - always

  # - name: check major version
  #   debug:
  #     var: ansible_distribution_major_version

  # - name: pip configure for ubuntu and cent7
  #   include_role:
  #     name: pip
  #   when: ansible_distribution_major_version|int > 6

  # - name: pip configure for cent6 (softnas)
  #   include_role:
  #     name: pip-centos6
  #   when: ansible_distribution_major_version|int <= 6

  roles:
  - role: 'newuser'
  - role: 'add-user-to-group'
    vars:
      variable_group: 'syscontrol'
    when: sudo | bool

  tasks:
  - name: reset ssh connection to allow user changes to affect 'current login user'
    meta: reset_connection

# we need to ensure the new user can login

- hosts: "{{ variable_host | default('ansible_control') }}" # check login is possible as user
  remote_user: "{{ variable_connect_as_user | default('deployuser') }}"
  gather_facts: false
  become: false

  vars:
    variable_user: deadlineuser
    sudo: true

  pre_tasks:
  - name: Wait 10 seconds - Test connection for new user - no sudo
    wait_for_connection:
      timeout: 10
    register: result
    failed_when: result['failed']
    become_user: "{{ variable_user }}"

- hosts: "{{ variable_host | default('ansible_control') }}" # check login is possible as user
  remote_user: "{{ variable_connect_as_user | default('deployuser') }}"
  gather_facts: true
  become: true

  vars:
    ansible_become_pass: "{{ user_deadlineuser_pw }}"
    ansible_password: "{{ user_deadlineuser_pw }}"
    variable_user: deadlineuser
    sudo: true

  pre_tasks:
  - name: Wait 10 seconds - Test connection for new user - with sudo
    wait_for_connection:
      timeout: 10
    register: result
    failed_when: result['failed']
    become_user: "{{ variable_user }}"
    become: true
    when: sudo | bool