- hosts: firehawkgateway
  gather_facts: "{{ variable_gather_facts | default('false') }}"
  become: true
  remote_user: deployuser
  become_user: root
  vars_files:
    - /deployuser/ansible/group_vars/all/vars

  vars:
    spot_template_path: '/secrets/spot-fleet-templates/config.json'
    # ensure a spot template in your secrets path per the deadline spot plugin instructions on the thiunkbox website.
    # the contents of this json file will be written to the deadline db.

  roles:
  - {role: 'firehawkvfx.deadline.deadline_spot', tags: 'update'}